spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path= /api/student/**
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path= /api/address/**
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
server:
  port: 9090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
